// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"hatbo5cfli","name":"AdminDataCRUD","description":"","endpoint":"https://hatbo5cfli.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/AdminData","/AdminData/123"]},{"id":"dmohfxsr1e","name":"sampleCloudApi","description":"","endpoint":"https://dmohfxsr1e.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:de28e384-e39c-4566-8ab0-c802d52b4e0f',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'adminsmartbin-hosting-mobilehub-1500935095',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dvifvg9dzwbd2.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"adminsmartbin-mobilehub-1500935095-AdminData","attributes":[{"name":"user_Id","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"user_Id"}],
    'aws_mobile_analytics_app_id': '3ef2e48cd2314b00b6f14f58eeff2eac',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e91329ef-c852-48ce-bf6f-ece15a9f2fbd',
    'aws_project_name': 'AdminSmartBin',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'adminsmartbin-deployments-mobilehub-1500935095',
    'aws_resource_name_prefix': 'adminsmartbin-mobilehub-1500935095',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'adminsmartbin-userfiles-mobilehub-1500935095',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_XzEkTBFEa',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7i1dur137ob1f880smrch8dfjg',
    'aws_appsync_graphqlEndpoint': 'https://w23goy5wgrcxxm6i3255wyzt5u.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
