// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"n7jdlp9io8","name":"User_TableCRUD","description":"","endpoint":"https://n7jdlp9io8.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/User_Table","/User_Table/123"]},{"id":"4bilobqysk","name":"BinData","description":"","endpoint":"https://4bilobqysk.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/BinData","/BinData/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:6d900264-befd-4c8d-9f28-0a0dd2f40837',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'smartbin-hosting-mobilehub-102009816',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3ipchqs6dzvqw.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"smartbin-mobilehub-102009816-User_Table","attributes":[{"name":"user_id","type":"S"},{"name":"Email_id","type":"S"},{"name":"Mobile_no","type":"N"},{"name":"Username","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"user_id"}],
    'aws_mobile_analytics_app_id': '94502a2df1e64c298f098f62b024ec56',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'd6be9215-d044-4b67-b686-73a75377187e',
    'aws_project_name': 'SmartBin',
    'aws_project_region': 'us-east-1',
    'aws_push_pinpoint': 'enable',
    'aws_resource_bucket_name': 'smartbin-deployments-mobilehub-102009816',
    'aws_resource_name_prefix': 'smartbin-mobilehub-102009816',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'smartbin-userfiles-mobilehub-102009816',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_mBSlIcK9W',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '3oo39043296o9a2jq7nq9t0bih',
    'aws_appsync_graphqlEndpoint': 'https://mmypsnk3yzaufghx4xnqyg5swq.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
