// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"ilni5jx9e1","name":"User_TableCRUD","description":"","endpoint":"https://ilni5jx9e1.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/User_Table","/User_Table/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:e850c18c-4fea-4662-a11f-d713ca545e2c',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'techbinapp-hosting-mobilehub-1928256020',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3hkoua7ya2hv1.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"techbinapp-mobilehub-1928256020-User_Table","attributes":[{"name":"userId","type":"S"},{"name":"Name","type":"S"},{"name":"Email_id","type":"S"},{"name":"Mobile_no","type":"N"},{"name":"No_of_time_dump","type":"N"},{"name":"Password","type":"S"},{"name":"Points","type":"N"},{"name":"Reward_id","type":"SS"},{"name":"Total_dump","type":"N"}],"indexes":[{"indexName":"Login","hashKey":"userId","rangeKey":"Email_id"}],"region":"us-east-1","hashKey":"userId","rangeKey":"Name"}],
    'aws_mobile_analytics_app_id': '488ab5ab6ab747e4ba13116495400e02',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '0542e00d-87bc-47ff-a6cd-0db1bd88e717',
    'aws_project_name': 'techbinApp',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'techbinapp-deployments-mobilehub-1928256020',
    'aws_resource_name_prefix': 'techbinapp-mobilehub-1928256020',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'techbinapp-userfiles-mobilehub-1928256020',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_hXJojS11F',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '482v7mkk12kkqcser3m6pn08ba',
    'aws_appsync_graphqlEndpoint': 'https://t5f227edxjfqxhpmsw4nxezyoy.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile;
