// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:51434979-7c0e-4f8a-81e8-f1fe0b06707d',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'collectorapphackatho-hosting-mobilehub-1643497789',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2ozam9qa0y1kf.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'e07668c634884d55998239a5bb373f4b',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'c887d8df-75f7-4fd9-b3cc-fc884199f437',
    'aws_project_name': 'collectorApphackathon',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'collectorapphackatho-mobilehub-1643497789',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'collectorapphackatho-userfiles-mobilehub-1643497789',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_lPjcdGeZZ',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '203jmkdlciabmrpkbpsgchobln',
    'aws_appsync_graphqlEndpoint': 'https://57ysyjgrcvatfer2depzcctfou.appsync-api.us-east-1.amazonaws.com/graphql',
    'aws_appsync_region': 'us-east-1',
    'aws_appsync_authenticationType': 'AWS_IAM',
}

export default awsmobile;
